### ISSUE TITLE
question about cardiac atlas

### ISSUE THREAD

**Issue by luo-cool** [yuan-xiaohan/Slice-mask-based-3D-Cardiac-Shape-Reconstruction#1]
Hi, Yuan:
How can I obtain atlas maps for other organs? I would like to reconstruct other organs, but I don't know how to obtain .obj samples. If you can provide a response, I would greatly appreciate it.

**Comment by yuan-xiaohan** [comment]
You can segment the desired organ and then directly apply the marching cubes algorithm to it using modules such as trimesh, mcubes, or pymeshlab. Alternatively, you can extract the segmented contour and save it in point cloud format, which can be imported into software like Meshlab to apply the marching cubes algorithm. Finally, you can save the resulting mesh as an .obj file.
