### ISSUE TITLE
Chamfer distance and mean surface distance calculation

### ISSUE THREAD

**Issue by SKaushalya98** [yuan-xiaohan/Slice-mask-based-3D-Cardiac-Shape-Reconstruction#4]
Hi Yuan, 

Can you please explain chow to calculate hamfer distance and mean surface distance to evaluate the results on test data. I can not find those in metrics.py.

Thank you.

**Comment by yuan-xiaohan** [comment]
points_error has been added in metrics.py. Thank you for your correction.
